-- Oracle bootstrap unico (Live SQL + Oracle Cloud Free Tier)
-- Este script cria a tabela/indices principais se ainda nao existirem
-- e executa checagens de dicionario para validacao em laboratorio.
-- Otimizado para cenario ESP32 + MPU6050 via hotspot celular.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE sensor_data (
      id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_id        VARCHAR2(64) NOT NULL,
      ts_epoch         NUMBER(18,6) NOT NULL,
      temperature      NUMBER(10,4),
      vibration        NUMBER(10,4),
      accel_x_g        NUMBER(10,4),
      accel_y_g        NUMBER(10,4),
      accel_z_g        NUMBER(10,4),
      gyro_x_dps       NUMBER(10,4),
      gyro_y_dps       NUMBER(10,4),
      gyro_z_dps       NUMBER(10,4),
      fan_state        VARCHAR2(20),
      cmd_speed_label  VARCHAR2(16),
      rot_state_label  VARCHAR2(16),
      use_state_label  VARCHAR2(16),
      vib_profile_label VARCHAR2(16),
      label_source     VARCHAR2(16) DEFAULT 'CONTROL',
      transition_marker NUMBER(1) DEFAULT 0,
      sample_rate      NUMBER(10,3) DEFAULT 10,
      collection_id    VARCHAR2(64),
      connection_type  VARCHAR2(16) DEFAULT 'WIFI',
      ssid             VARCHAR2(64),
      rssi             NUMBER(6,1),
      created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Indices essenciais para consultas de serie temporal e filtragem
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_device ON sensor_data(device_id)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_ts_epoch ON sensor_data(ts_epoch)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_collection ON sensor_data(collection_id)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_fan_state ON sensor_data(fan_state)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_cmd_speed_label ON sensor_data(cmd_speed_label)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_rot_state_label ON sensor_data(rot_state_label)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_use_state_label ON sensor_data(use_state_label)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_vib_profile_label ON sensor_data(vib_profile_label)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_label_combo ON sensor_data(cmd_speed_label, rot_state_label, use_state_label, vib_profile_label)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_connection_type ON sensor_data(connection_type)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_ssid ON sensor_data(ssid)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Migracao incremental: adicionar colunas se tabela ja existir sem elas
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE sensor_data ADD (connection_type VARCHAR2(16) DEFAULT ''WIFI'')'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE sensor_data ADD (ssid VARCHAR2(64))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE sensor_data ADD (rssi NUMBER(6,1))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- Checagens de dicionario
SELECT table_name FROM user_tables WHERE table_name = 'SENSOR_DATA';
SELECT index_name, table_name FROM user_indexes WHERE table_name = 'SENSOR_DATA' ORDER BY index_name;
SELECT column_name, data_type, nullable FROM user_tab_columns WHERE table_name = 'SENSOR_DATA' ORDER BY column_id;
