-- Oracle-first reset script for ESP32 MPU6050 project
-- Inclui colunas de conectividade para rastreio hotspot/wifi

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE sensor_data PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE sensor_data (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id        VARCHAR2(64) NOT NULL,
  ts_epoch         NUMBER(18,6) NOT NULL,
  temperature      NUMBER(10,4),
  vibration        NUMBER(10,4),
  accel_x_g        NUMBER(10,4),
  accel_y_g        NUMBER(10,4),
  accel_z_g        NUMBER(10,4),
  gyro_x_dps       NUMBER(10,4),
  gyro_y_dps       NUMBER(10,4),
  gyro_z_dps       NUMBER(10,4),
  fan_state        VARCHAR2(20),
  cmd_speed_label  VARCHAR2(16),
  rot_state_label  VARCHAR2(16),
  use_state_label  VARCHAR2(16),
  vib_profile_label VARCHAR2(16),
  label_source     VARCHAR2(16) DEFAULT 'CONTROL',
  transition_marker NUMBER(1) DEFAULT 0,
  sample_rate      NUMBER(10,3) DEFAULT 10,
  collection_id    VARCHAR2(64),
  connection_type  VARCHAR2(16) DEFAULT 'WIFI',
  ssid             VARCHAR2(64),
  rssi             NUMBER(6,1),
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_device ON sensor_data(device_id);
CREATE INDEX idx_ts_epoch ON sensor_data(ts_epoch);
CREATE INDEX idx_collection ON sensor_data(collection_id);
CREATE INDEX idx_fan_state ON sensor_data(fan_state);
CREATE INDEX idx_cmd_speed_label ON sensor_data(cmd_speed_label);
CREATE INDEX idx_rot_state_label ON sensor_data(rot_state_label);
CREATE INDEX idx_use_state_label ON sensor_data(use_state_label);
CREATE INDEX idx_vib_profile_label ON sensor_data(vib_profile_label);
CREATE INDEX idx_label_combo ON sensor_data(cmd_speed_label, rot_state_label, use_state_label, vib_profile_label);
CREATE INDEX idx_connection_type ON sensor_data(connection_type);
CREATE INDEX idx_ssid ON sensor_data(ssid);
